language: php
php:
  - 7.2
  - 7.3
  - nightly

before_script:
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse src --level 7
